/// Flutter icons MyIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const String? _kFontPkg = null;

  static const IconData type_regular__state_outline__library_arrow___left_2 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_arrow___right_2 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_arrow___up_2 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_bag = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_calling = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_discount = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_filter = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_heart = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_home = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_more_circle = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_notification = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_search = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_star = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData type_regular__state_outline__library_arrow___down_2 = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
